export const ADD_CAR_START = "ADD_CAR_START";
export const ADD_CAR_SUCCESS = "ADD_CAR_SUCCESS";

export const FETCH_CARS_START = "FETCH_CARS_START";
export const FETCH_CARS_SUCCESS = "FETCH_CARS_SUCCESS";
export const FETCH_CARS_FAIL = "FETCH_CARS_FAIL";
